name: CI
on:
  push:
    branches: [ develop ]
    tags-ignore:
      - '*'
  pull_request:
    branches: [ develop ]
permissions:
    actions: none
    checks: none
    contents: write
    deployments: none
    id-token: none
    issues: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
env:
  GITHUB_TOKEN_RELEASE_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
  USE_HARD_LINKS: 'false'
jobs:
  build:
    if: "github.event_name == 'pull_request' || !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.runson }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - osarch: windows-intel
            runson: windows-latest
            packscript: package:win:portable
            arch: x64
            release_tag: latest-windows-intel
          - osarch: windows-arm
            runson: windows-latest
            packscript: package:win:portable
            arch: arm64
            release_tag: latest-windows-arm
          - osarch: macos-intel
            runson: macos-latest
            packscript: package:mac:skip-notarize
            arch: x64
            release_tag: latest-macos-intel
          - osarch: macos-arm
            runson: macos-latest
            packscript: package:mac:skip-notarize
            arch: arm64
            release_tag: latest-macos-arm
          - osarch: linux-intel
            runson: ubuntu-22.04
            packscript: package:linux:portable
            arch: x64
            release_tag: latest-linux-intel
          - osarch: linux-arm
            runson: ubuntu-22.04
            packscript: package:linux:portable
            arch: arm64
            release_tag: latest-linux-arm
    env:
      RELEASE_TAG: ${{ matrix.release_tag }}
    steps:
    - run: pwdx || echo OK || true
      shell: cmd
      continue-on-error: true
    - name: Microsoft Windows dumpbin to PATH
      if: startsWith(matrix.osarch, 'windows-')
      run: >
        $VS_ROOT = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"; $VS_VERSION = (Get-ChildItem -Path $VS_ROOT | Sort-Object Name -Descending | Select-Object -First 1).Name; $VS_BIN = "$VS_ROOT\$VS_VERSION\bin\Hostx64\x64"; echo $VS_BIN >> $env:GITHUB_PATH; echo $VS_BIN
      shell: powershell
    - name: Microsoft Windows dumpbin check
      if: startsWith(matrix.osarch, 'windows-')
      run: >
        dumpbin /headers "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\dumpbin.exe" | findstr /i machine
      shell: cmd
    - run: echo 'RELEASE_TAG:' ${{ env.RELEASE_TAG }}
    - run: 'echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"'
    - run: 'echo "GITHUB_RUN_ID: ${{ github.run_id }}"'
    - run: 'echo "GITHUB_SHA: ${{ github.sha }}"'
    - run: echo "${{ matrix.osarch }} // ${{ runner.arch }}"
    - name: System arch (non Windows)
      if: ${{ !startsWith(matrix.osarch, 'windows-') }}
      run: uname -m && arch
    - name: Checkout
      uses: actions/checkout@v4
    - name: Git config global dump (post)
      run: 'git config --global --list || echo NO_GIT_GLOBAL_CONFIG || true'
      shell: bash
    - name: Git config local dump (post)
      run: 'git config --list || echo NO_GIT_GLOBAL_CONFIG || true'
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: node --version && npm --version
    - run: npm --global install npm@^11
    - run: npm --version
    - run: python --version || echo ok || true
    - run: python3 --version || echo ok || true
    - run: pip --version || echo ok || true
    - run: python3 -m pip install setuptools || python -m pip install setuptools
    - name: package patch 1
      run: node scripts/package-ci-patch.js package.json ${{ github.run_id }} && cat package.json | grep -i VERSION && cat package.json
      shell: bash
    - name: package patch 2
      run: node scripts/package-ci-patch.js src/package.json ${{ github.run_id }} && cat src/package.json | grep -i VERSION && cat src/package.json
      shell: bash
    - name: package lock patch
      run: node scripts/package-lock-patch.js && cat package-lock.json | grep -i divina-player-js
      shell: bash
    - run: git --no-pager diff
    - run: npm cache clean --force
    - run: npm cache verify
    - run: cat package-lock.json | grep -i divina-player-js
    - name: NPM install (arm64)
      if: endsWith(matrix.osarch, '-arm')
      run: npm ci --foreground-scripts --arch=arm64 --cpu=arm64
    - name: NPM install (x64)
      if: endsWith(matrix.osarch, '-intel')
      run: npm ci --foreground-scripts --arch=x64 --cpu=x64
    - name: Electron version + arch (Windows)
      if: startsWith(matrix.osarch, 'windows-')
      run: >
        (dumpbin /headers "node_modules\electron\dist\electron.exe" | findstr /i machine) && (node_modules\\electron\\dist\\electron.exe --no-sandbox --version || echo INVALID_ARCH || true) && (node_modules\\electron\\dist\\electron.exe --no-sandbox --abi || echo INVALID_ARCH || true)
      shell: cmd
      continue-on-error: true
    - name: Electron version + arch (Linux)
      if: startsWith(matrix.osarch, 'linux-')
      run: >
        (file node_modules/electron/dist/electron) && (node_modules/electron/dist/electron --no-sandbox --version || echo INVALID_ARCH || true) && (node_modules/electron/dist/electron --no-sandbox --abi || echo INVALID_ARCH || true)
    - name: Electron version + arch (MacOS)
      if: startsWith(matrix.osarch, 'macos-')
      run: >
        (file node_modules/electron/dist/Electron.app/Contents/MacOS/Electron) && (node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --no-sandbox --version || echo INVALID_ARCH || true) && (node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --no-sandbox --abi || echo INVALID_ARCH || true)
    - run: npm list -g node-gyp || echo ok || true
    - run: npm list node-gyp || echo ok || true
      continue-on-error: true
    - name: PR action (just build)
      if: ${{ github.event_name == 'pull_request' }}
      run: npm run build:prod
    - name: Build and Package (all non-PR)
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          node -e 'const path = require("path"); const fs = require("fs"); const filePath = path.join(process.cwd(), "package.json"); let fileStr = fs.readFileSync(filePath, { encoding: "utf8" }); fileStr = fileStr.replace(/--x64/g, "--arm64"); fs.writeFileSync(filePath, fileStr, { encoding: "utf8" });'
        else
          node -e 'const path = require("path"); const fs = require("fs"); const filePath = path.join(process.cwd(), "package.json"); let fileStr = fs.readFileSync(filePath, { encoding: "utf8" }); fileStr = fileStr.replace(/--arm64/g, "--x64"); fs.writeFileSync(filePath, fileStr, { encoding: "utf8" });'
        fi
        npm run ${{ matrix.packscript }}
      shell: bash
    - name: List release dir
      run: ls -al release || dir release
    - name: GitHub Tagged Release Delete/ReCreate and Upload Build Artefacts
      if: ${{ github.event_name != 'pull_request' }}
      run: node scripts/release-github.mjs
